[roomboss]
api_url = "https://api.roomboss.com/v1"
api_id = "holidayniseko"
api_key = "Deo6FYvVgtcmQMTU"


[snowflake]
account = "your-snowflake-account"
username = "your-username"
password = "your-password"
warehouse = "your-warehouse"
database = "your-database"


cognito_api_key = "eyJhbGciOiJIUzI1NiIsImtpZCI6Ijg4YmYzNWNmLWM3ODEtNDQ3ZC1hYzc5LWMyODczMjNkNzg3ZCIsInR5cCI6IkpXVCJ9.eyJvcmdhbml6YXRpb25JZCI6ImMxOTYxZGU1LTc1ODctNDY2OS04NWJhLTg2YzdlMzYzZjQ5NSIsImludGVncmF0aW9uSWQiOiI1NGZjODZjNy1lMmJiLTQwZjItOWNjMy0zMTQwZWFmYTQ3MmMiLCJjbGllbnRJZCI6IjNkZTNmODMwLWNiYzctNDZlNi1iOTZlLTVmMDE2NzcyMTgzMCIsImp0aSI6IjkwYzgzN2NlLWY1ZTEtNDZiOC1hODFkLTNjNTQ2ZDYzMzRkZiIsImlhdCI6MTcyODI4MzIwMiwiaXNzIjoiaHR0cHM6Ly93d3cuY29nbml0b2Zvcm1zLmNvbS8iLCJhdWQiOiJhcGkifQ.alC_ynDFjdweihuUn-cmlQkmj8No5R45VJlCDzONjHY"

ga4_prop_id = "385376735"
ga4_json_creds = "ga4-api-433110-70cce6ae2e08.json"

[general]
type = "service_account"
project_id = "ga4-api-433110"
private_key_id = "56cf3fa3e64b718f937404d62552043dbed39c1e"
private_key = '''-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCGD8oqLe/QKnon
cnzhFi5pmEjiC5BuNsuNBT4d1MK5aMwR5idWGQWD2ThslE2TrKhPg+omiC8J94GW
9jCVvJ9XHHFXl4TSqJ/xnQYA+/erl3PogCSPTCVqNHLrNGxQepMSdS0YyxPFL0vB
B2HVx5NjRReZRswfRw63AxT9g9fPwbN528OPMnMcvbJ32naDcrUT9+/ktfRGHHLc
hKFSrwyaTjb3M3tGB+bPz62ZoiXUmZwHzSGYvFZ5G13rEodPwcdFcTUt25wDkhz7
JVZCxzJlaOK4aTunTYWRwhFOvgoNXE8THUP9xQnxwUSqJflw0Ve+b3Ht5Rq+SbK+
hmhJExlrAgMBAAECggEADac9BSexhUdWMn9H9ZqPNoTiY1cfKgJdn6qZhWs+O6jP
I8GHXw7kT2XHh9NgxTnv2E1MgwkalU7GPWwsTYusxK/qYSvWxKeUxoQh8Oa4dhrS
HKs0Tf3Iz7SwwYCQyW96XAZgBebkyA/FjM6mKaIOQi1utlcOAd94Qa5ILHuJdqiT
U6VnUhzy0wdylm/HtQqEKKX9XSt7WE/mGqDtLcbwziQFcIdkyfTPNfCNXnNdXoVL
d1X+VLOLbGwFls9v179D+YkrP9A3EuVXMyk33TRSNmrR6Lwd5JnXT1pfhLSRTtzZ
tobOClzFGaxHAzV62R0rCuZMAg096o67sOsGVKgX3QKBgQC8lwwmlwUH4HS3NHV3
ACpYxt6gwz0++bLj6qM5UVytAGjPp7SQaYzrjBqAflxC8REH/lt+rpi6yf852cTL
ftmGkWnF0LZ2Qa8VSPIt6VefvgubRU6I1Pk1PrT2OBUz7RccLSjCV35nEpfXJT2m
rB//JYx3r3DGq12dWXr8+pxRPwKBgQC1+x6Cshe2X6g2Wn1AiALL1LxCcsVNbAu5
66WKpqpRce/aKZabzF4YBWjC5tBMBilmqHIg7BmXvBhczQzP40Zsvgi/UL0YSmBL
KZBDZH5/AcQE+noe5b9FGSDTPyi2FUtyoTQFByYJNHLe0fZ+R0WBU9qZusW4A/BZ
wa7DZpyA1QKBgQCknpktqk/q40Qek70hhlRwsA+vdx2kNiSwjKW0J9Bk92GGOhcE
pA4toluT5Dk2+eTq/F3zhAavrhmK7wu4sl7A93fEA/7x1T42rzkvWGtzdln9TI9U
I8vxbW5bKvNfI0sz/juBAQzGflVqqQha0A8SEj2+T7d6xCVwb6ZK45vF0wKBgHBT
ZG2/h6tmN+n0yMMAMNmnodxSAz7aphJIRZHjddV3wliiuvfHmXyyOguzdHa4hu16
o5d2pAVocJE3b+URn/KXCcctCsrnfbBnI0i1yu6SJG/+O0q+/OSlsgEyRuq9Eijb
H8TKuMuNuCmY59DiJSDCpXemNUx0AfMk/b5Wo9tRAoGAK6e5FtETOAptgIDBkpuA
ZPvJZP9z/LlVMTJS0+ksfrlU98KEjE4S8WFnwPuzr+yAdiv8aXhmBqvz1pY58Fp1
JsKjF1l3n+st13yPiSgcT0h6voHnda9ZPHXmqRboG+qqbIAy3K7mWY9VNZOrG9Zq
78vief3nGlhDAkn8YglkM6A=
-----END PRIVATE KEY-----'''
client_email = "ga4-api@ga4-api-433110.iam.gserviceaccount.com"
client_id = "107118296600325952742"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/ga4-api%40ga4-api-433110.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[gcp_service_account]
sheet_name = "All Bookings"